version: '3'
services:
    frontend:
        build: images/apache
        image: onyx/frontend
        volumes:
            - ..:/var/www/onyx
            - ../system/bash-history/.frontend:/root/.bash_history
        ports:
            - "${WEB_PORT}:80"
        links:
            - db
        environment:
            - USER_ID=${USER_ID}
            - GROUP_ID=${GROUP_ID}
    db:
        image: mariadb
        volumes:
            - ../var/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=onyx
            - MYSQL_PASSWORD=onyx
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "${PMA_PORT}:80"
        links:
            - db
        environment:
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=root
